# Generated by Django 6.0.6 on 2026-08-19 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='hospital.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_name',
            field=models.CharField(default='Unknown Patient', max_length=100),
            preserve_default=False,
        ),
    ]
